# Generated by Django 3.0.5 on 2020-05-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pro',
            field=models.URLField(blank=True, default='pro.jpeg'),
        ),
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.URLField(blank=True, default='pro.jpeg'),
        ),
    ]
